In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris


In [ ]:
iris=load_iris()
X=iris.data
y=iris.target
X.shape
X

In [25]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
# combient d'exemple de chaque classe4
np.bincount(iris.target)

array([50, 50, 50])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
X_train

In [29]:
#construire le model
modelarbre=DecisionTreeClassifier()
modelarbre.fit(X_train,y_train)

DecisionTreeClassifier()

In [30]:
#calculer le taux de perfermance
t=modelarbre.score(X_train,y_train)
print("le taux = ",t)

le taux =  1.0


In [31]:
#calculer le taux de perfermance
t=modelarbre.score(X_test,y_test)
print("le taux = ",t)

le taux =  0.9333333333333333


In [35]:
# 1,10
#5,10
#6,10
ndepth=6
nsplit=10
modelarbre=DecisionTreeClassifier(max_depth=ndepth,min_samples_split=nsplit)
modelarbre.fit(X_train,y_train)
t=modelarbre.score(X_test,y_test)
print("le taux = ",t)


le taux =  0.9333333333333333


In [38]:
#test
z=[[1.0,1.0,3.3,8.89]]
pz=modelarbre.predict(z)
pz

array([1])